# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: debug-statements
    -   id: detect-private-key
    -   id: check-merge-conflict
-   repo: https://github.com/PyCQA/isort
    rev: master
    hooks:
    -   id: isort
        args:
        -   --profile
        -   black
-   repo: https://github.com/psf/black
    rev: master
    hooks:
    -   id: black
    -   id: black-jupyter
